modLoader="javafml"
loaderVersion="[36,35,34,33,32)"
license="GNU General Public License Version 3.0"
issueTrackerURL="https://github.com/PugsMods/WoneWay/issues"
[[mods]]
modId="woneway"
version="1.0.0BETA-8"
displayName="WoneWay"
updateJSONURL="https://raw.githubusercontent.com/PugsMods/WoneWay/master/src/main/java/com/putopug/woneway/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/woneway"
logoFile="woneway.png"
credits="LeeTheSoloGamer - Bugtesting"
authors="PugzAreCute_"
description='''A Mod which adds one way blocks!!'''
[[dependencies.woneway]]
    modId="forge"
    mandatory=true
    versionRange="[32,36)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woneway]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
