modLoader="javafml"
loaderVersion="[35,)"
license="GNU General Public License Version 3.0"
issueTrackerURL="https://github.com/PugsMods/WoneWay/issues"
[[mods]]
modId="woneway"
version="1.0.0BETA"
displayName="WoneWay"
updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/woneway"
logoFile="examplemod.png"
credits="LeeTheSoloGamer - Bugtesting"
authors="PugzAreCute_"
description='''
A Mod which adds one way blocks!!
'''
[[dependencies.woneway]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.woneway]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
