#!/usr/bin/python3

#  This file is part of WoneWay.
#
#  WoneWay is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  WoneWay is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with WoneWay.  If not, see <https://www.gnu.org/licenses/>.

# The WoneWay Language Generation Script!
#
# This script is used to automatically generate language files for woneway
# blocks from the id list located in [This Folder]/generated/input_global.txt
#
# If you want to use this script, please remember the following things
#
# 1. This script must be runt from this directory only. If you run it from another folder, the
# generated/input_global.txt must be located it that file.
#
# 2. The last JSON generated by this will also have a comma(","), so while using it please remove that.
import re

inputFilePath = "generated/input_global.txt"
inputFile = open(inputFilePath)
outFile = open("generated/output_lang.txt", "a")

for x in inputFile:
    x = x.splitlines()[0]
    print("block.woneway." + x + ":\"" + re.sub("_", " ", x).title() + "\",")
    outFile.write("\"block.woneway." + x + "\":\"" + re.sub("_", " ", x).title() + "\",")
    outFile.write("\r")
outFile.close()
inputFile.close()
