modLoader = "javafml"
loaderVersion = "[37,)"
license = "GNU GPL v3"
issueTrackerURL = "https://github.com/PugsMods/WoneWay/issues"
[[mods]]
modId = "woneway"
version = "1.0.6"
displayName = "WoneWay"
updateJSONURL = "https://raw.githubusercontent.com/PugsMods/WoneWay/master/src/main/java/com/putopug/woneway/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/woneway"
logoFile = "WoneWay.png"
credits = "LeeTheSoloGamer - Bugtesting"
authors = "PugzAreCute_"
description = '''A Mod which adds one way blocks!!'''
[[dependencies.woneway]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.woneway]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
