# Import Dependencies
import re

# User input goes here
GEN_INPUT = ['SEETHROUGH_CYAN_GLAZED_TERRACOTTA', 'SEETHROUGH_CYAN_SHULKER_BOX', 'SEETHROUGH_CYAN_STAINED_GLASS', 'SEETHROUGH_CYAN_TERRACOTTA', 'SEETHROUGH_CYAN_WOOL', 'SEETHROUGH_DARK_OAK_LEAVES', 'SEETHROUGH_DARK_OAK_LOG', 'SEETHROUGH_DARK_OAK_PLANKS', 'SEETHROUGH_DARK_OAK_WOOD', 'SEETHROUGH_DARK_PRISMARINE', 'SEETHROUGH_DEAD_BRAIN_CORAL_BLOCK', 'SEETHROUGH_DEAD_BUBBLE_CORAL_BLOCK', 'SEETHROUGH_DEAD_FIRE_CORAL_BLOCK', 'SEETHROUGH_DEAD_TUBE_CORAL_BLOCK', 'SEETHROUGH_DIAMOND_BLOCK', 'SEETHROUGH_DIAMOND_ORE', 'SEETHROUGH_DIORITE', 'SEETHROUGH_DIRT', 'SEETHROUGH_DISPENSER', 'SEETHROUGH_DRIED_KELP_BLOCK', 'SEETHROUGH_DROPPER', 'SEETHROUGH_EMERALD_BLOCK', 'SEETHROUGH_EMERALD_ORE', 'SEETHROUGH_END_STONE', 'SEETHROUGH_END_STONE_BRICKS', 'SEETHROUGH_FIRE_CORAL_BLOCK', 'SEETHROUGH_FLETCHING_TABLE', 'SEETHROUGH_FURNACE', 'SEETHROUGH_GILDED_BLACKSTONE', 'SEETHROUGH_GLASS', 'SEETHROUGH_GLOWSTONE', 'SEETHROUGH_BLOCK_OF_GOLD', 'SEETHROUGH_GOLD_ORE', 'SEETHROUGH_GRANITE', 'SEETHROUGH_GRASS_BLOCK', 'SEETHROUGH_GRAY_CONCRETE', 'SEETHROUGH_GRAY_CONCRETE_POWDER', 'SEETHROUGH_GRAY_GLAZED_TERRACOTTA', 'SEETHROUGH_GRAY_SHULKER_BOX', 'SEETHROUGH_GRAY_STAINED_GLASS', 'SEETHROUGH_GRAY_TERRACOTTA', 'SEETHROUGH_GRAY_WOOL', 'SEETHROUGH_GREEN_CONCRETE', 'SEETHROUGH_GREEN_CONCRETE_POWDER', 'SEETHROUGH_GREEN_GLAZED_TERRACOTTA', 'SEETHROUGH_GREEN_SHULKER_BOX', 'SEETHROUGH_GREEN_STAINED_GLASS', 'SEETHROUGH_GREEN_TERRACOTTA', 'SEETHROUGH_GREEN_WOOL', 'SEETHROUGH_HAY_BALE', 'SEETHROUGH_HONEY_BLOCK', 'SEETHROUGH_HONEYCOMB_BLOCK', 'SEETHROUGH_HORN_CORAL_BLOCK', 'SEETHROUGH_ICE', 'SEETHROUGH_INFESTED_CHISELED_STONE_BRICKS', 'SEETHROUGH_INFESTED_COBBLESTONE', 'SEETHROUGH_INFESTED_CRACKED_STONE_BRICKS', 'SEETHROUGH_INFESTED_MOSSY_STONE_BRICKS', 'SEETHROUGH_INFESTED_STONE', 'SEETHROUGH_INFESTED_STONE_BRICKS', 'SEETHROUGH_IRON_BLOCK', 'SEETHROUGH_IRON_ORE', 'SEETHROUGH_JACK_O_LANTERN', 'SEETHROUGH_JUKEBOX', 'SEETHROUGH_JUNGLE_LEAVES', 'SEETHROUGH_JUNGLE_LOG', 'SEETHROUGH_JUNGLE_PLANKS', 'SEETHROUGH_JUNGLE_WOOD', 'SEETHROUGH_LAPIS_BLOCK', 'SEETHROUGH_LAPIS_ORE', 'SEETHROUGH_LIGHT_BLUE_CONCRETE', 'SEETHROUGH_LIGHT_BLUE_CONCRETE_POWDER', 'SEETHROUGH_LIGHT_BLUE_GLAZED_TERRACOTTA', 'SEETHROUGH_LIGHT_BLUE_SHULKER_BOX', 'SEETHROUGH_LIGHT_BLUE_STAINED_GLASS', 'SEETHROUGH_LIGHT_BLUE_TERRACOTTA', 'SEETHROUGH_LIGHT_BLUE_WOOL', 'SEETHROUGH_LIGHT_GRAY_CONCRETE', 'SEETHROUGH_LIGHT_GRAY_CONCRETE_POWDER', 'SEETHROUGH_LIGHT_GREY_GLAZED_TERRACOTTA', 'SEETHROUGH_LIGHT_GRAY_SHULKER_BOX', 'SEETHROUGH_LIGHT_GREY_STAINED_GLASS', 'SEETHROUGH_LIGHT_GREY_TERRACOTTA', 'SEETHROUGH_LIGHT_GREY_WOOL', 'SEETHROUGH_LIME_CONCRETE', 'SEETHROUGH_LIME_CONCRETE_POWDER', 'SEETHROUGH_LIME_GLAZED_TERRACOTTA', 'SEETHROUGH_LIME_SHULKER_BOX', 'SEETHROUGH_LIME_STAINED_GLASS', 'SEETHROUGH_LIME_TERRACOTTA', 'SEETHROUGH_LIME_WOOL', 'SEETHROUGH_LODESTONE', 'SEETHROUGH_LOOM', 'SEETHROUGH_MAGENTA_CONCRETE', 'SEETHROUGH_MAGENTA_CONCRETE_POWDER', 'SEETHROUGH_MAGENTA_GLAZED_TERRACOTTA', 'SEETHROUGH_MAGENTA_SHULKER_BOX', 'SEETHROUGH_MAGENTA_STAINED_GLASS', 'SEETHROUGH_MAGENTA_TERRACOTTA', 'SEETHROUGH_MAGENTA_WOOL', 'SEETHROUGH_MAGMA_BLOCK', ]
PREFIX = "seethrough"
EXTENDS = "SeeThroughBlock"
FILENAME = "Output.java"
REGISTER = "ITEMS"

# Code To Generate Lines
# Iterate Through Every Object In GEN_INPUT
for index in GEN_INPUT:
    # Strip all spaces
    stripped = re.sub("\s", "_", index)
    stripped_prefix = re.sub("\s", "_", PREFIX)
    stripped_extends = re.sub("\s", "_", EXTENDS)
    stripped_fn = re.sub("\s", "_", FILENAME)
    stripped_reg = re.sub("\s", "_", REGISTER)
    # Open the file
    createJAVA = open(stripped_fn, "a")

    # Write to the file
    createJAVA.write(
        "public static final RegistryObject<Item> " +stripped.upper()+"_ITEM" + " = " + stripped_reg + '.register("' +
        stripped.lower() + '",' + '()'+" -> new BlockItemBase("+stripped+".get()));\n""")
    # Print to the console
    print("Generating syntax for :" + index)
