xw = '"block.combat7.craftox": "Craftox Workspace",'
# Import Dependencies
import re

# User input goes here
GEN_INPUT = ['ACACIA_LEAVES', 'ACACIA_LOG', 'ACACIA_PLANKS', 'ACACIA_WOOD', 'ANCIENT_DEBRIS', 'ANDESITE', 'BARREL', 'BASALT', 'BEDROCK', 'BEE_NEST', 'BEEHIVE', 'BIRCH_LEAVES', 'BIRCH_LOG', 'BIRCH_PLANKS', 'BIRCH_WOOD', 'BLACK_CONCRETE', 'BLACK_CONCRETE_POWDER', 'BLACK_GLAZED_TERRACOTTA', 'BLACK_SHULKER_BOX', 'BLACK_STAINED_GLASS', 'BLACK_TERRACOTTA', 'BLACK_WOOL', 'BLACKSTONE', 'BLAST_FURNACE', 'BLUE_CONCRETE', 'BLUE_CONCRETE_POWDER', 'BLUE_GLAZED_TERRACOTTA', 'BLUE_ICE', 'BLUE_SHULKER_BOX', 'BLUE_STAINED_GLASS', 'BLUE_TERRACOTTA', 'BLUE_WOOL', 'BONE_BLOCK', 'BOOKSHELF=', 'BRAIN_CORAL_BLOCK', 'BRICKS', 'BROWN_CONCRETE', 'BROWN_CONCRETE_POWDER', 'BROWN_GLAZED_TERRACOTTA', 'BROWN_MUSHROOM_BLOCK', 'BROWN_SHULKER_BOX', 'BROWN_STAINED_GLASS', 'BROWN_TERRACOTTA', 'BROWN_WOOL', 'BUBBLE_CORAL_BLOCK', 'CARTOGRAPHY_TABLE', 'CARVED_PUMPKIN', 'CHAIN_COMMAND_BLOCK', 'CHISELED_NETHER_BRICKS', 'CHISELED_POLISHED_BLACKSTONE', 'CHISELED_RED_SANDSTONE', 'CHISELED_SANDSTONE', 'CHISELED_STONE_BRICKS', 'CLAY_BLOCK', 'COAL_BLOCK', 'COAL_ORE', 'COARSE_DIRT', 'COBBLESTONE', 'COMMAND_BLOCK', 'CRACKED_NETHER_BRICKS', 'CRACKED_POLISHED_BLACKSTONE_BRICKS', 'CRACKED_STONE_BRICKS', 'CRAFTING_TABLE', 'CRIMSON_HYPHAE', 'CRIMSON_NYLIUM', 'CRIMSON_PLANKS', 'CRIMSON_STEM', 'CRYING_OBSIDIAN', 'CUT_RED_SANDSTONE', 'CUT_SANDSTONE', 'CYAN_CONCRETE', 'CYAN_CONCRETE_POWDER', 'CYAN_GLAZED_TERRACOTTA', 'CYAN_SHULKER_BOX', 'CYAN_STAINED_GLASS', 'CYAN_TERRACOTTA', 'CYAN_WOOL', 'DARK_OAK_LEAVES', 'DARK_OAK_LOG', 'DARK_OAK_PLANKS', 'DARK_OAK_WOOD', 'DARK_PRISMARINE', 'DEAD_BRAIN_CORAL_BLOCK', 'DEAD_BUBBLE_CORAL_BLOCK', 'DEAD_FIRE_CORAL_BLOCK', 'DEAD_TUBE_CORAL_BLOCK', 'DIAMOND_BLOCK', 'DIAMOND_ORE', 'DIORITE', 'DIRT', 'DISPENSER', 'DRIED_KELP_BLOCK', 'DROPPER', 'EMERALD_BLOCK', 'EMERALD_ORE', 'END_STONE', 'END_STONE_BRICKS', 'FIRE_CORAL_BLOCK', 'FLETCHING_TABLE', 'FURNACE', 'GILDED_BLACKSTONE', 'GLASS', 'GLOWSTONE', 'BLOCK_OF_GOLD', 'GOLD_ORE', 'GRANITE', 'GRASS_BLOCK', 'GRAY_CONCRETE', 'GRAY_CONCRETE_POWDER', 'GRAY_GLAZED_TERRACOTTA', 'GRAY_SHULKER_BOX', 'GRAY_STAINED_GLASS', 'GRAY_TERRACOTTA', 'GRAY_WOOL', 'GREEN_CONCRETE', 'GREEN_CONCRETE_POWDER', 'GREEN_GLAZED_TERRACOTTA', 'GREEN_SHULKER_BOX', 'GREEN_STAINED_GLASS', 'GREEN_TERRACOTTA', 'GREEN_WOOL', 'HAY_BALE', 'HONEY_BLOCK', 'HONEYCOMB_BLOCK', 'HORN_CORAL_BLOCK', 'ICE', 'INFESTED_CHISELED_STONE_BRICKS', 'INFESTED_COBBLESTONE', 'INFESTED_CRACKED_STONE_BRICKS', 'INFESTED_MOSSY_STONE_BRICKS', 'INFESTED_STONE', 'INFESTED_STONE_BRICKS', 'IRON_BLOCK', 'IRON_ORE', 'JACK_O_LANTERN', 'JUKEBOX', 'JUNGLE_LEAVES', 'JUNGLE_LOG', 'JUNGLE_PLANKS', 'JUNGLE_WOOD', 'LAPIS_BLOCK', 'LAPIS_ORE', 'LIGHT_BLUE_CONCRETE', 'LIGHT_BLUE_CONCRETE_POWDER', 'LIGHT_BLUE_GLAZED_TERRACOTTA', 'LIGHT_BLUE_SHULKER_BOX', 'LIGHT_BLUE_STAINED_GLASS', 'LIGHT_BLUE_TERRACOTTA', 'LIGHT_BLUE_WOOL', 'LIGHT_GRAY_CONCRETE', 'LIGHT_GRAY_CONCRETE_POWDER', 'LIGHT_GREY_GLAZED_TERRACOTTA', 'LIGHT_GRAY_SHULKER_BOX', 'LIGHT_GREY_STAINED_GLASS', 'LIGHT_GREY_TERRACOTTA', 'LIGHT_GREY_WOOL', 'LIME_CONCRETE', 'LIME_CONCRETE_POWDER', 'LIME_GLAZED_TERRACOTTA', 'LIME_SHULKER_BOX', 'LIME_STAINED_GLASS', 'LIME_TERRACOTTA', 'LIME_WOOL', 'LODESTONE', 'LOOM', 'MAGENTA_CONCRETE', 'MAGENTA_CONCRETE_POWDER', 'MAGENTA_GLAZED_TERRACOTTA', 'MAGENTA_SHULKER_BOX', 'MAGENTA_STAINED_GLASS', 'MAGENTA_TERRACOTTA', 'MAGENTA_WOOL', 'MAGMA_BLOCK']
MODID = "woneway"
PREFIX = "seethrough"
FILENAME = "en_us.json"

# Code To Generate Lines
# Iterate Through Every Object In GEN_INPUT
# Open the file
stripped_fn = re.sub("\s","_",FILENAME.lower())
createJSON = open(stripped_fn, "a")
createJSON.write("{\n")
for index in GEN_INPUT:
    # Strip all spaces
    index = re.sub("\s","_",index)
    stripped = re.sub("\s", "_", index)
    stripped_prefix = re.sub("\s", "_", PREFIX.lower())
    stripped_MODID = re.sub("\s", "_", MODID.lower())
    stripped_id = re.sub("_"," ",stripped)
    # Write to the file
    createJSON.write('"block.'+stripped_MODID+"."+stripped_prefix.lower()+"_"+index.lower()+'" :'+' "'+stripped_prefix.title()+" "+stripped_id.title()+'",\n')
    # Print to the console
    print("Generating lang for :" + index)
createJSON.write("}")