# Import Dependencies
import re

# User input goes here
GEN_INPUT = ['CYAN_GLAZED_TERRACOTTA', 'CYAN_SHULKER_BOX', 'CYAN_STAINED_GLASS', 'CYAN_TERRACOTTA', 'CYAN_WOOL', 'DARK_OAK_LEAVES', 'DARK_OAK_LOG', 'DARK_OAK_PLANKS', 'DARK_OAK_WOOD', 'DARK_PRISMARINE', 'DEAD_BRAIN_CORAL_BLOCK', 'DEAD_BUBBLE_CORAL_BLOCK', 'DEAD_FIRE_CORAL_BLOCK', 'DEAD_TUBE_CORAL_BLOCK', 'DIAMOND_BLOCK', 'DIAMOND_ORE', 'DIORITE', 'DIRT', 'DISPENSER', 'DRIED_KELP_BLOCK', 'DROPPER', 'EMERALD_BLOCK', 'EMERALD_ORE', 'END_STONE', 'END_STONE_BRICKS', 'FIRE_CORAL_BLOCK', 'FLETCHING_TABLE', 'FURNACE', 'GILDED_BLACKSTONE', 'GLASS', 'GLOWSTONE', 'BLOCK_OF_GOLD', 'GOLD_ORE', 'GRANITE', 'GRASS_BLOCK', 'GRAY_CONCRETE', 'GRAY_CONCRETE_POWDER', 'GRAY_GLAZED_TERRACOTTA', 'GRAY_SHULKER_BOX', 'GRAY_STAINED_GLASS', 'GRAY_TERRACOTTA', 'GRAY_WOOL', 'GREEN_CONCRETE', 'GREEN_CONCRETE_POWDER', 'GREEN_GLAZED_TERRACOTTA', 'GREEN_SHULKER_BOX', 'GREEN_STAINED_GLASS', 'GREEN_TERRACOTTA', 'GREEN_WOOL', 'HAY_BALE', 'HONEY_BLOCK', 'HONEYCOMB_BLOCK', 'HORN_CORAL_BLOCK', 'ICE', 'INFESTED_CHISELED_STONE_BRICKS', 'INFESTED_COBBLESTONE', 'INFESTED_CRACKED_STONE_BRICKS', 'INFESTED_MOSSY_STONE_BRICKS', 'INFESTED_STONE', 'INFESTED_STONE_BRICKS', 'IRON_BLOCK', 'IRON_ORE', 'JACK_O_LANTERN', 'JUKEBOX', 'JUNGLE_LEAVES', 'JUNGLE_LOG', 'JUNGLE_PLANKS', 'JUNGLE_WOOD', 'LAPIS_BLOCK', 'LAPIS_ORE', 'LIGHT_BLUE_CONCRETE', 'LIGHT_BLUE_CONCRETE_POWDER', 'LIGHT_BLUE_GLAZED_TERRACOTTA', 'LIGHT_BLUE_SHULKER_BOX', 'LIGHT_BLUE_STAINED_GLASS', 'LIGHT_BLUE_TERRACOTTA', 'LIGHT_BLUE_WOOL', 'LIGHT_GRAY_CONCRETE', 'LIGHT_GRAY_CONCRETE_POWDER', 'LIGHT_GREY_GLAZED_TERRACOTTA', 'LIGHT_GRAY_SHULKER_BOX', 'LIGHT_GREY_STAINED_GLASS', 'LIGHT_GREY_TERRACOTTA', 'LIGHT_GREY_WOOL', 'LIME_CONCRETE', 'LIME_CONCRETE_POWDER', 'LIME_GLAZED_TERRACOTTA', 'LIME_SHULKER_BOX', 'LIME_STAINED_GLASS', 'LIME_TERRACOTTA', 'LIME_WOOL', 'LODESTONE', 'LOOM', 'MAGENTA_CONCRETE', 'MAGENTA_CONCRETE_POWDER', 'MAGENTA_GLAZED_TERRACOTTA', 'MAGENTA_SHULKER_BOX', 'MAGENTA_STAINED_GLASS', 'MAGENTA_TERRACOTTA', 'MAGENTA_WOOL', 'MAGMA_BLOCK']
INIT_CLASS = "WoneWayBlocks"
prefix = "SEETHROUGH"
FILENAME = "Output.java"

# Code To Generate Lines
# Iterate Through Every Object In GEN_INPUT
for index in GEN_INPUT:
    # Strip all spaces
    stripped = re.sub("\s", "_", index)
    stripped_init = re.sub("\s", "_", INIT_CLASS)
    stripped_prefix = re.sub("\s", "_", prefix)
    stripped_fn = re.sub("\s", "_", FILENAME)
    # Open the file
    createJAVA = open(stripped_fn, "a")

    # Write to the file
    createJAVA.write("RenderTypeLookup.setRenderLayer("+stripped_init+"."+stripped_prefix.upper()+"_"+stripped.upper()+".get(), RenderType.getCutout());\n")
    # Print to the console
    print("Generating syntax for :" + index)
